name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-versions: [1.13, 1.14, 1.15]
        os: [ ubuntu-18.04, macos-10.15 ] # TODO: pass linters on 'windows-2019'

    steps:

    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-versions }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/oikomi/OctopusServer

    - name: Build
      run: make all
      working-directory: src/github.com/oikomi/OctopusServer

    - name: Test
      run: make test
      working-directory: src/github.com/oikomi/OctopusServer
